import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <section className="bg-black text-white min-h-screen">
          {children}
        </section>
        <footer>
          <div className="w-full text-center mx-auto font-medium bg-purple-300 text-black">
            © 2024 Career Map , All rights reserved
          </div>
        </footer>
      </body>
    </html>
  );
}
